### ISSUE TITLE
Parse error when load .env file

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#144]
After @hernanmd #142 PR, we are able to load .env environment, but there is still parse errors, like for example in : ``CMConwayModel>>initCustomMap``
where cormas.env is loaded.

Cormas.env file start like that:
```
dimensions	50 50
cloture	torroidal
connexite	eight
backgroundColor	0.500061 0.500061 0.500061
attributs	state(Symbol)
dead
dead
dead
dead
dead
...
```

Apparently the problem appears because of ``backgroundColor`` before ``attributs`` is not parse correctly.

**Comment by SergeStinckwich** [comment]
Remove the line from "backgroundColor	0.500061 0.500061 0.500061"

**Comment by hernanmd** [comment]
Thanks Serge, I'm writing .env tests right now. Will use that.

**Comment by SergeStinckwich** [comment]
In fact, cormas.env is part of asset.zip that is located here: https://github.com/cormas/cormas/tree/master/resources
Why not having the assets directly in an assets directory in cormas git repository?

**Comment by hernanmd** [comment]
@nbecu [proposed](https://github.com/cormas/cormas/issues/49) to have a separate repository for each model, and I created some time ago repositories for each model (ECEC, Conway, etc) because the idea was people can fork/clone a model separately from the Cormas repo code. But I cannot find the repositories now, maybe they were deleted?

So this would mean to keep including the models in the same Cormas code repository?

**Comment by SergeStinckwich** [comment]
Yes I remove them because they are completely desynchronised with the actual model in the image. For the moment let’s keep everything simple by having just one repository with all the core models inside. We can revise this when we have too much models.

**Comment by tomooda** [comment]
Can we close this issue?
