### ISSUE TITLE
Programming menu doesn't work

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#158]
When I try to create a new model (but it seems to be the same with existing one) I do not have access to the well-known IDE.
 ![](https://hackmd.iscpif.fr/uploads/upload_f3a115d473db483f4cfda6daacae44cd.png)

**Comment by SergeStinckwich** [comment]
Sorry, but what is a well-know IDE 😕 ?

**Comment by hernanmd** [comment]
@ElCep I could take a look this week-end. First I want to finish parsing the .env files in Pharo.

**Comment by ElCep** [comment]
looking at @tomooda 's answer, I'm thinking maybe it's actually creating a model that doesn't work.

**Comment by SergeStinckwich** [comment]
We spend sometimes with @tomooda on this issue, but difficult to understand where is the problem without the help of @hernanmd

**Comment by hernanmd** [comment]
@ElCep model operation menu entries are disabled when a model is not opened in the UI. When a model is created or opened, then the menu entries are enabled.

Maybe what you've seen was related with broken/dettached FSM state when a model was not created, opened or closed correctly - and this was because of missing features on the UI code, not your fault at all. Some menu entries were disabled when the model was opened which was wrong. A fix for this it's requested in https://github.com/cormas/cormas/pull/279

Let us know other issues.

**Comment by SergeStinckwich** [comment]
#279 has been integrated. @ElCep can you check again the issue that you mention here. You can reopen a new one if needed.

**Comment by ElCep** [comment]
At the moment Cormas GUI is completely broken.

**Comment by SergeStinckwich** [comment]
It works better now for me ;-)

**Comment by ElCep** [comment]
:-) 

![](https://hackmd.iscpif.fr/uploads/upload_f4888ac0eceecd02f58614e540431c6e.png)

**Comment by SergeStinckwich** [comment]
You need to update ProjectFramework
