### ISSUE TITLE
timeStep and timeStepValue on CormasModel

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#159]
``CormasModel`` define ``timeStep`` and ``timeStepValue`` that apparently return the same value. Can we just keep ``timeStep`` ?

**Comment by pierbo** [comment]
Yes sure! timeStepValue is a ValueHolder (that is used for the interfaces)

**Comment by tomooda** [comment]
I'm moving the timeStep management to the instance side of CMAbstractModel. I'll use `ObservableSlot` to manage the change event handling instead of `ValueHolder`. I also found that `HistogramsInterface` subscribes to the change of timeStep. In the case that user want to do similar subscription, I will implement `whenTimeStepChangedDo:`.

**Comment by tomooda** [comment]
Okay, `ObservableSlot` is not available in Pharo 7. CMAbstractModel already provides `CMTimeChangedAnnouncement` when the `timeStep` has changed. I'll stop using ObservableSlot and re-implement `whenTimeStepChangedDo:` so that client code can subscribe to the change notification of `timeStep`

**Comment by tomooda** [comment]
created a Pull Request https://github.com/cormas/cormas/pull/172

**Comment by SergeStinckwich** [comment]
I think we could use ObservableSlot because we are using Pharo 8.0 now for last version of CORMAS.

**Comment by tomooda** [comment]
Client code can receive the change of `timeStep` by `CMTimeChangedAnnouncement`. I added `whenTimeStepChangedDo:` and `whentimeStepChangedSend:to:` methods to `CMAbstractModel` for subscribing notification. UI components can use this API to refresh visuals. I think the code now looks simpler than before. :smile:
