### ISSUE TITLE
What is the purpose of CMBasicEntityInspector and CMEntityInspector ?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#165]
What is the purpose of ``CMBasicEntityInspector`` and ``CMEntityInspector`` ?
Propose specific inspector on ``CMEntity`` but why two classes then?
They could be replaced by specific inspector views defined on ``CMEntity``.

**Comment by pierbo** [comment]
These two classes have been designed by Nicolas in order to open small inspectors on entities. A double click on an agent, opens a small windows showing its attributes and values. As this small interface has been created on the GUI Painter Tool of VW, it cannot work on Pharo.
Perhaps we could remove these classes for the moment?

**Comment by nbecu** [comment]
Sure.
No worries

Le jeu. 11 juin 2020 à 22:20, Pierre Bommel <notifications@github.com> a
écrit :
