### ISSUE TITLE
New model from Cormas Interface doesn't work

### ISSUE THREAD

**Issue by pierbo** [cormas/cormas#170]
When using the Cormas main interface, there are problems for creating a new model.
The first steps work well:
- Menu -> New => open a simple dialog window to enter the name of the model
<img width="450" alt="image" src="https://user-images.githubusercontent.com/7630722/85126627-252a7280-b22e-11ea-9295-f5338c11fc0a.png">

- Then another window opens to set the meta-data of this model (version name, creation date, comments, etc):

<img width="598" alt="image" src="https://user-images.githubusercontent.com/7630722/85126781-6ae73b00-b22e-11ea-9f7c-9b10847a33e7.png">
After that, there are problems:

- The title of the Cormas interface is not updated, 
- None of the sub-menus of "Programming" works.

**Comment by hernanmd** [comment]
Hi Pierre, I will have a look into this.

**Comment by SergeStinckwich** [comment]
I'm not sure, we should have a window like that when you create a new model. The user does not know the version s/he will create and with github we don't need to have a versioning system inside Cormas. Many users might be involved for a model. 

We should use the model class comment instead of having something specific that is never updated. In Pharo 9.0, class comments can be written in Markdown and this will ease the task of users.

**Comment by hernanmd** [comment]
This cormas model metadata editor window was unfinished, model was not updated, so[ this PR](https://github.com/cormas/cormas/pull/279) just make it work by saving whatever the user entered in the text fields and text area in the Model Comments. It is also accessible going through File -> Properties, when a model is opened or created.

Now with this PR also the version is displayed in the window title so the user is aware and increment version whenever is needed.

Although I like distributed versioning system, I don't know in this case how a user could be aware of Github versioning from inside the Cormas UI. IMO it could require some UX or prototyping before just coding.

For example does this mean to force users to use Github over other repositories (Gitlab, Bitbucket, etc)? Also versions now are "self-contained" in a method in a Cormas model (currently a .st file), maybe Github is a bit over-engineered solution for non-developers and integrating it into the UI in an usable way may not be so trivial. 

Since this was just fixing we could open another issue for discussing this topic?

**Comment by hernanmd** [comment]
Please don't forget to update ProjectFramework package in your image **before** pulling.

**Comment by SergeStinckwich** [comment]
Thank you Hernan for the update about this issue.

I'm not pushing the idea that CORMAS users should use github versioning system. Maybe later if we have a more transparent layer on top of github.

We should think about how users can release their models and for this discussion we will need the help of @pierbo and @ElCep I guess. 

For me the current versioning CORMAS process is pointless, because nobody is using it, versions, comments became obsolete and this is not possible to come back to a previous version of the model.

One easy solution for the moment, would be to be able to comment a model in order to put whatever you want: description of the model, authors, examples, version number, ...
