### ISSUE TITLE
What should we do with methods in deprecated category in CormasModel ?

### ISSUE THREAD

**Issue by SergeStinckwich** [cormas/cormas#19]
There is a lot of methods in deprecated category of CormasModel class (66 classes):

```
CormasModel methodsInProtocol: 'deprecated'
```

What should we do with them ?

**Comment by nbecu** [comment]
as for the issue about IndexedSet, your question leads back to another question.
Do we want to keep some king of compatibility with the models developed under cormas/vw.

Because, actually the deprecated protocol is often use to store all methods, that might be still called by old models and that we keep there when we release a new version.

So 
- if we decide not to try to have a compatibility with models developed in vw, then we can delete all those deprecated methods
- if we try to have this compatibilty, we should keep them

**Comment by SergeStinckwich** [comment]
At the moment, what is important is not compatibility with old CORMAS models.
What is important now is to have something working, even if we break compatibility.

This is not a good idea to have a lot of deprecated methods. We don't even know in which CORMAS versions these methods works. We should use the Pharo deprecated API.

Action: remove old and deprecated code in the Pharo version. We will fix the old models later.

**Comment by SergeStinckwich** [comment]
We have to look at the senders of these methods. If they have no sender (or the sender is also deprecated), we can safely remove them.

**Comment by SergeStinckwich** [comment]
Some methods like CormasModel>>updateAgents are still use in Cormas-core.

**Comment by SergeStinckwich** [comment]
We should remove all methods that are in deprecated categories or with deprecated comments.
