### ISSUE TITLE
asRational in pharo is asFraction

### ISSUE THREAD

**Issue by ElCep** [cormas/cormas#34]
Hi, 
This function doesn't work anymore. In pharo, `asRational` doesn't exist. It's `asFraction` I guess.
I don't know (yet) how to fix it and if `asRational` exist in other cormas part. 

```Smalltalk
randomFloatFrom: startNumber to: endNumber
	"Purpose: Return a random float between 'startNumber' and 'endNumber' (excluding startNumber and endNumber): 
	startNumber < randomFloat < endNumber, ie. randomFloat ‚Ç¨ ]startNumber ; endNumber[.
Examples: Cormas randomFloatFrom: 0 to: 10.
		Cormas randomFloatFrom: -4.1 to: 2.5
		10 timesRepeat: [Cormas randomFloatFrom: 1.1 to: 2.9] => (2.19661 1.78905 1.19457 1.96943 1.6194 1.12104 1.94028 2.41498 2.19254 2.18504) "
	
	| extent result |
	extent := endNumber asRational - startNumber asRational.
	result := (Cormas random * extent + startNumber asRational) asFloat.
	^result = endNumber
		ifTrue: [self randomFloatFrom: startNumber to: endNumber]
		ifFalse: [result]
```

**Comment by SergeStinckwich** [comment]
Yes I guess ```asRational``` is ```asFraction``` in Pharo :-)

**Comment by SergeStinckwich** [comment]
If you look at senders of ```asRational```, you will find 3 methods that send this message (including ```randomFloatFrom:to:```. Try to find them and fix them :-)

**Comment by SergeStinckwich** [comment]
So if I correct this method and fix a little bit the comment, you will have something like : 

```Smalltalk
randomFloatFrom: startNumber to: endNumber
	"Purpose: Return a random float between 'startNumber' and 'endNumber' (excluding startNumber and endNumber): 
	startNumber < randomFloat < endNumber
Examples: Cormas randomFloatFrom: 0 to: 10.
		Cormas randomFloatFrom: -4.1 to: 2.5
		10 timesRepeat: [Cormas randomFloatFrom: 1.1 to: 2.9] => (2.19661 1.78905 1.19457 1.96943 1.6194 1.12104 1.94028 2.41498 2.19254 2.18504) "
	
	| extent result |
	extent := endNumber asFraction - startNumber asFraction.
	result := (Cormas random * extent + startNumber asFraction) asFloat.
	^result = endNumber
		ifTrue: [self randomFloatFrom: startNumber to: endNumber]
		ifFalse: [result]

**Comment by SergeStinckwich** [comment]
Now what is important now, this is wrote also an unit test that will check that the behavior of this method is correct. Can you wrote one in your commit ? :-)

**Comment by SergeStinckwich** [comment]
Now, I don't like using this kind of ```Cormas XXX``` utilities methods. Why not using plain Pharo instead ? For example ```Cormas random``` to generate a random number., can be replace by : ```Random next```.

**Comment by nbecu** [comment]
Random next will be more elegant. I agree.

Actually,  perhaps "Random float" would be even better because this method
is supposed to return a float between 0 and 1


The other method would then be "Random from: to:"


Le ven. 13 avr. 2018 05:27, Serge Stinckwich <notifications@github.com> a
écrit :

**Comment by SergeStinckwich** [comment]
```Random next``` is part of Pharo API. We can introduce new API but you break all the habits of usual Pharo developers.

Having a lot of utilities methods in the ```Cormas``` class is a bad habits, especially if they re-implement existing functionalities. I guess we can remove them step by step in order to simplify the class.

Regarding random numbers, in PolyMath project we have different RNG (Random Number Generator) and various probability distributions. Which one do we like to use ? Do we offer to users the possibility to change the RNG and/or distributions ? Random number control are quite important in simulation frameworks.

**Comment by SergeStinckwich** [comment]
I start a discussion on pharo-users mailing-list on Random API : http://lists.pharo.org/pipermail/pharo-users_lists.pharo.org/2018-April/038744.html
One nice proposition is to have : 
- ```Float randomFrom: 1.2 to:4.5.```
- ```Integer randomFrom: -1 to:10. ```

**Comment by ElCep** [comment]
Hi, 
I have close this issue because @SergeStinckwich open an other one  :+1: https://github.com/cormas/cormas/issues/35
