### ISSUE TITLE
Task: Develop a Roassal-Cormas package

### ISSUE THREAD

**Issue by nbecu** [cormas/cormas#44]
Integrate CORMAS more with Roassal : http://agilevisualization.com/
The idea here is to be able to script a simulation very easily and to build a visualisation with Roassal engine.

**Comment by brun0** [comment]
- Good news: Interaction of the user with Roassal elements seems very nice and easy.
- I created a new class in cormas-ui called CMDraggableSpatialEntity. I understand it as a feature that you can add to all graphical elements representing cormas SpatialEntities. 
- You can test in CMFiremanModel example9: Now, when you select a point representing a fireman and drag and drop it to a location (I only tested inside the space) and the fireman will move to the new spot.
- I add the feature at the moment when agent views are created in the CMSimulationGrid (at the initialisation and during the simu), so all your models should benefit this (i created example 5 in ECEC for instance that only go slower so that you can catch the agents..)
-Note that once you have defined the feature, it is very easy to add it to ellements. i only added one line  in the functions were entity views are created: (
"newSituatedEntitiesViews do: [:nse | nse @ CMDraggableSituatedEntity  ]"
). 

And if you look at the class "CMDraggableSituatedEntity" you can see that it is very simple (only one method) because it inheritates from a roassal class doing most of the job.

**Comment by olekscode** [comment]
This package already exists. The space view of Cormas is implemented with Roassal3, the probe charts are currently on Roassal2 but will soon be migrated to Roassal3
